// event_queue.rs — host-owned FIFO queue for generated Result Anchors
//
// After one evaluation finishes and creates a standard Result Anchor, the host
// places that Anchor at the end of this queue.  The outer coordinator then
// drains the queue one item at a time, in stable first-in-first-out order,
// without recursive stack execution, parallel evaluation, or retry.
//
// A Result Anchor generated by a queued evaluation is appended to the tail.
// It must not jump ahead of events already waiting.

use std::collections::VecDeque;

use crate::result_anchor::ResultAnchor;

/// A process-local, in-memory FIFO queue of exact Result Anchors.
///
/// The queue owns typed `ResultAnchor` values rather than loosely structured
/// JSON, so follow-up request construction can read exact fields without
/// re-parsing.
pub struct ResultEventQueue {
    pending: VecDeque<ResultAnchor>,
}

impl ResultEventQueue {
    pub fn new() -> Self {
        Self {
            pending: VecDeque::new(),
        }
    }

    /// Append a Result Anchor to the tail of the queue.
    pub fn enqueue(&mut self, anchor: ResultAnchor) {
        self.pending.push_back(anchor);
    }

    /// Remove and return the oldest Result Anchor from the front.
    pub fn pop_front(&mut self) -> Option<ResultAnchor> {
        self.pending.pop_front()
    }
}

impl Default for ResultEventQueue {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::result_anchor::{ResultAnchor, ResultAnchorKind};
    use serde_json::json;

    fn sample_anchor(event_id: &str) -> ResultAnchor {
        ResultAnchor::new(
            ResultAnchorKind::Succeeded(json!({"status": "recorded"})),
            "eval_001",
            "action_1",
            "lantern.task.record",
            1,
            "sha256:abc123",
            "lantern-local",
            1720000000000,
            "evt_root_001",
            "evt_root_001",
            1,
        )
        .with_event_id(event_id)
    }

    #[test]
    fn empty_queue_is_empty_and_pops_nothing() {
        let mut queue = ResultEventQueue::new();
        assert!(queue.pop_front().is_none());
    }

    #[test]
    fn enqueue_then_pop_front_returns_fifo_order() {
        let mut queue = ResultEventQueue::new();
        queue.enqueue(sample_anchor("a/result"));
        queue.enqueue(sample_anchor("b/result"));
        queue.enqueue(sample_anchor("c/result"));
        assert_eq!(queue.pop_front().unwrap().event_id, "a/result");
        assert_eq!(queue.pop_front().unwrap().event_id, "b/result");
        assert_eq!(queue.pop_front().unwrap().event_id, "c/result");
        assert!(queue.pop_front().is_none());
    }

    #[test]
    fn enqueue_during_draining_appends_to_tail() {
        let mut queue = ResultEventQueue::new();
        queue.enqueue(sample_anchor("first/result"));
        queue.enqueue(sample_anchor("second/result"));

        // Pop first, then enqueue a new one before popping second.
        let _first = queue.pop_front().unwrap();
        queue.enqueue(sample_anchor("third/result"));

        assert_eq!(queue.pop_front().unwrap().event_id, "second/result");
        assert_eq!(queue.pop_front().unwrap().event_id, "third/result");
        assert!(queue.pop_front().is_none());
    }

    // -----------------------------------------------------------------------
    // Test 5 (queue-level): A newly generated event never jumps ahead of an
    // existing sibling.  When the processor of the head enqueues a child while
    // a sibling is still in the queue, the child must be ordered after it.
    // -----------------------------------------------------------------------
    #[test]
    fn child_never_jumps_ahead_of_existing_sibling() {
        let mut queue = ResultEventQueue::new();
        // Already waiting: head and sibling.
        queue.enqueue(sample_anchor("head/result"));
        queue.enqueue(sample_anchor("sibling/result"));

        // Processor of the head decides to enqueue a child before the sibling
        // is popped.  The child must land behind the sibling.
        let _head = queue.pop_front().unwrap();
        queue.enqueue(sample_anchor("head-child/result"));

        assert_eq!(
            queue.pop_front().unwrap().event_id,
            "sibling/result",
            "sibling must still be ahead of the head's child"
        );
        assert_eq!(queue.pop_front().unwrap().event_id, "head-child/result");
        assert!(queue.pop_front().is_none());
    }

    // -----------------------------------------------------------------------
    // Test 6 (queue-level): A simulated outer drain maintains depth 1.
    // The test counts the live "in-flight" anchor count across the whole
    // drain and asserts the maximum is exactly 1.
    // -----------------------------------------------------------------------
    #[test]
    fn drain_maintains_maximum_depth_one() {
        use std::cell::Cell;

        let mut queue = ResultEventQueue::new();
        for id in ["a/result", "b/result", "c/result"] {
            queue.enqueue(sample_anchor(id));
        }

        let in_flight = Cell::new(0u32);
        let observed_max = Cell::new(0u32);
        let mut drained = Vec::<String>::new();
        while let Some(anchor) = queue.pop_front() {
            in_flight.set(in_flight.get() + 1);
            let current = in_flight.get();
            if current > observed_max.get() {
                observed_max.set(current);
            }
            assert!(
                in_flight.get() <= 1,
                "drain depth must never exceed 1, observed {}",
                in_flight.get()
            );
            // Simulate the inner processing: it may enqueue at most one new
            // child per parent.  The child is appended, never re-entered
            // during this very iteration.
            drained.push(anchor.event_id.clone());
            in_flight.set(in_flight.get() - 1);
        }
        assert_eq!(observed_max.get(), 1, "max in-flight depth must be 1");
        assert_eq!(
            drained,
            vec![
                "a/result".to_string(),
                "b/result".to_string(),
                "c/result".to_string()
            ]
        );
    }

    // -----------------------------------------------------------------------
    // Test 7 (queue-level): `ResultEventQueue` is `Send` under the current
    // representation.  It wraps `VecDeque<ResultAnchor>`, and `ResultAnchor`
    // is composed only from `Send` types, so the queue may be moved between
    // threads.  We assert that property at compile time.
    //
    // `Send` only means the value *may* be moved between threads.  It does not
    // create parallel evaluation.  Tethers still evaluates queued Result
    // Anchors one at a time: the coordinator owns the queue and drains it via
    // `pop_front`, and no worker pool, thread, async runtime, channel, lock,
    // or retry loop exists.  Seriality is an execution design enforced by the
    // coordinator and the explicit mutable-queue drain, not by a fake `!Send`
    // marker bolted onto the type.  Do not add `PhantomData`, `Rc`, `Cell`,
    // or raw pointers merely to force `!Send`.
    // -----------------------------------------------------------------------
    #[test]
    fn queue_value_is_send_under_current_representation() {
        fn assert_send<T: Send>() {}
        assert_send::<ResultEventQueue>();
    }

    // -----------------------------------------------------------------------
    // Test 8 (queue-level): The queue is process-local and lives in memory.
    // Its content is lost when dropped.  A drop mid-drain simply discards
    // remaining items without a retry surface.
    // -----------------------------------------------------------------------
    #[test]
    fn drop_discards_remaining_anchors_without_retry() {
        let mut queue = ResultEventQueue::new();
        queue.enqueue(sample_anchor("a/result"));
        queue.enqueue(sample_anchor("b/result"));
        let _ = queue.pop_front();
        drop(queue);
        // Nothing to assert beyond the fact that the drop did not panic
        // and that no Anchor reappeared.  The assertion is the
        // success of this test.
    }

    // -----------------------------------------------------------------------
    // Test 9 (queue-level): A failed pop does not reinsert the failed item.
    // The drainer sees `None` and stops; nothing is restored.
    // -----------------------------------------------------------------------
    #[test]
    fn failed_pop_does_not_reinsert() {
        let mut queue = ResultEventQueue::new();
        queue.enqueue(sample_anchor("a/result"));
        let first = queue.pop_front();
        assert!(first.is_some());
        // Simulate the processor returning an error before producing
        // a valid response: no requeue, no retry.
        let next = queue.pop_front();
        assert!(next.is_none(), "drainer must not silently retry");
        assert!(queue.pop_front().is_none());
    }

    // -----------------------------------------------------------------------
    // Test 10 (queue-level): Newly generated children land at the tail even
    // when the queue is being drained from the head, and the FIFO invariant
    // is preserved across a multi-generation drain.
    // -----------------------------------------------------------------------
    #[test]
    fn multi_generation_drain_preserves_fifo() {
        let mut queue = ResultEventQueue::new();
        queue.enqueue(sample_anchor("g1-a/result"));
        queue.enqueue(sample_anchor("g1-b/result"));

        let mut order = Vec::<String>::new();
        while let Some(anchor) = queue.pop_front() {
            order.push(anchor.event_id.clone());
            // Each generation-1 anchor enqueues one generation-2 child.
            if anchor.event_id.starts_with("g1-") {
                queue.enqueue(sample_anchor("g2-child/result"));
            }
        }
        assert_eq!(
            order,
            vec![
                "g1-a/result".to_string(),
                "g1-b/result".to_string(),
                "g2-child/result".to_string(),
                "g2-child/result".to_string(),
            ],
            "FIFO order must be preserved across generations"
        );
    }
}
