[licenses]
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "CC0-1.0",
    "BSL-1.0",
]
confidence-threshold = 0.8

[[licenses.exceptions]]
crate = "tethers-reference-host"
allow = ["MIT"]

[bans]
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
ignore = []
